### ISSUE TITLE
Problem for Macbook with M1

### ISSUE THREAD

**Issue by DmitriyDem** [spryker/docker-jenkins#6]
Hello. Can not build container for spryker/jenkins, container is unhealthy. 
Also checked that image https://hub.docker.com/r/spryker/jenkins was updated 2 years ago and can't work with linux/arm64
Any issue to avoid problem with jenkins for new Macbook?

**Comment by crisalder2806** [comment]
I got the same problem and still not sure how to fix this. Without jenkins it doesn't seem to work correctly.

**Comment by alexanderM91** [comment]
https://github.com/spryker/docker-sdk/issues/192#issuecomment-950894157
